#!/usr/bin/env bash
# Displays To infinity and beyond indefinitely with a sleep 2 and i am invinc

while true
do
    echo "To infinity and beyond"
    sleep 2
    trap 'echo "I am invincible!!!"' SIGTERM
done
