#!/usr/bin/env bash
# displays numbers fro 1 to 20.

C=1
while [ $C -le 20 ]
do
echo "$C";
case $C in
    4) echo "bad luck from China";;
    9) echo "bad luck from Japan";;
    17) echo "bad luck from Italy";;
esac
    C=$(( C + 1 ))
done
