#!/usr/bin/env bash
# displays the minutes and hours


HOUR=0
while [ $HOUR -le 12 ]
do
     echo "Hour: $HOUR";
     MINUTE=1;
     while [ $MINUTE -lt 60 ]
     do
         echo "$MINUTE";
	 MINUTE=$(( MINUTE + 1));
     done
     HOUR=$((HOUR + 1))
done
