#!/usr/bin/env bash
# displays the minutes and hours


$HOUR=0
while [ $HOUR -lt 13 ]
do
     echo "Hour: $HOUR"
     MINUTE=1
     while [MINUTE -lt 60 ]
     do
         echo $MINUTE
	 let MINUTE+=1
     done
     let HOUR+=1
done
